### ISSUE TITLE
Fix in api.rb, line 19

### ISSUE THREAD

**Issue by frankelia** [krismartin/clarifai-ruby#1]
I think line 19 should be:
`self.access_token = get_access_token[:access_token] if (!self.access_token || self.access_token.empty?)`

I think the `.blank?` function you used is Rails specific, and not checking if `access_token` is actually nil, before checking if it's empty, will give a NoMethodError (if the default access token is set to nil in the configuration.rb file)

**Comment by krismartin** [comment]
Good picked up. I've fixed it in master.
